title = "marrakechdunesr custom rules"
[allowlist]
description = "allow placeholders and docs"
paths = [
'''^.?env.example$''',
'''^docs/''',
'''^CI-CD-README.md$''',
'''^DEPLOY_CHECKS.md$'''
]
regexes = [
'''mongodb+srv://<username>:<password>@<cluster>.mongodb.net/<database>?retryWrites=true&w=majority''',
'''example-not-a-secret-.*''',
'''^Marrakech@2025$'''
]
[[rules]]
id = "mongodb-atlas-uri"
description = "MongoDB Atlas connection string"
regex = '''mongodb+srv://[^:\s]+:[^@\s]+@[^.\s]+.mongodb.net/[^\s"'?]+(?[^\s"']+)?'''
tags = ["key","mongodb"]
