title = "MarrakechDunesR gitleaks"

# Basic custom rule for MongoDB URIs (RE2; no (?:...) etc.)
[[rules]]
id = "mongodb-uri"
description = "MongoDB connection string"
regex = '''mongodb(\+srv)?:\/\/[A-Za-z0-9._%+-]+:[^@ \t\n\r]{6,}@[^^\/ \t\n\r]+\/[^\s"'?]+'''
tags = ["key", "mongodb", "secret"]

[allowlist]
# Example files and binary dirs that should not fail the scan
paths = [
  '''^\.env\.example$''',
  '''^docs/''',
  '''^attached_assets/''',
  '''^test-results/'''
]
# Explicitly allow the sample placeholder value in .env.example
regexes = [
  '''mongodb\+srv:\/\/username:password@cluster\.mongodb\.net\/database-name'''
]
