title = "MarrakechDunesR gitleaks (RE2 safe)"

[allowlist]
# These folders may contain fixtures or docs; don't blow up the scan.
paths = [
  "docs/*",
  "e2e/*",
  "test-results/*"
]

# A placeholder pattern we intentionally allow in .env.example:
regexes = [
  '''MONGODB_URI=YOUR_MONGODB_URI'''
]
