title = "MarrakechDunesR gitleaks"
# Keep it RE2-compatible (no lookbehind, no PCRE).
[[rules]]
id = "mongo_uri"
description = "Potential MongoDB connection URI with credentials"
regex = '''mongodb(+srv)?://[^/\s:@]+:[^/\s@]+@[^/\s]+/[^\s"']+'''
tags = ["secret","mongo"]

[allowlist]

# Ignore docs and the example env file
paths = [
'''^.env.example$''',
'''^docs/.*'''
]

# Ignore obvious placeholders
regexes = [
'''YOUR_MONGODB_URI''',
'''your-secure-.*'''
]

