title = "MarrakechDunes Gitleaks"

[allowlist]
description = "Allowed test/placeholder content"
paths = [
  '''^\.env\.example$''',
  '''^attached_assets/'''
]
regexes = [
  '''your-(jwt|session|super?admin)-password(-here)?''',
  '''mongodb\+srv://your-username:your-password@cluster\.mongodb\.net/database-name'''
]

[[rules]]
id = "mongodb-cred-uri"
description = "MongoDB URI with embedded credentials"
regex = '''mongodb(\+srv)?:\/\/[^:@\s]+:[^@\s]+@[^\/\s]+\/[^\s]*'''
tags = ["key","mongodb","secret"]

[[rules]]
id = "jwt-secret"
description = "Looks like a JWT secret"
regex = '''(?i)(jwt[_-]?secret)\s*[:=]\s*["']?[A-Za-z0-9_\-\.]{16,}["']?'''
tags = ["secret","generic"]

[[rules]]
id = "generic-secret"
description = "Generic secret-style assignment"
regex = '''(?i)(secret|api[_-]?key|token|passwd|password)\s*[:=]\s*["']?[A-Za-z0-9_\-\.]{12,}["']?'''
tags = ["secret","generic"]
