[global]
# Allow typical files but catch URIs and JWT-looking strings
[[rules]]
id = "mongodb-connection-string"
description = "MongoDB connection string"
regex = '''mongodb(\+srv)?://[^\s'"]+'''
tags = ["key", "database"]

[[rules]]
id = "jwt-secret"
description = "JWT secret"
regex = '''JWT_SECRET\s*=\s*[A-Za-z0-9_\-\.]+'''
tags = ["key", "jwt"]

[[rules]]
id = "session-secret"
description = "Session secret"
regex = '''SESSION_SECRET\s*=\s*[A-Za-z0-9_\-\.]+'''
tags = ["key", "session"]

[[rules]]
id = "admin-password"
description = "Admin password"
regex = '''ADMIN_PASSWORD\s*=\s*.*$'''
tags = ["key", "password"]

[[rules]]
id = "superadmin-password"
description = "Super admin password"
regex = '''SUPERADMIN_PASSWORD\s*=\s*.*$'''
tags = ["key", "password"]

# Allow typical files
[[rules]]
id = "allow-package-json"
description = "Allow package.json"
regex = '''package\.json'''
tags = ["allowlist"]

[[rules]]
id = "allow-lockfiles"
description = "Allow lockfiles"
regex = '''package-lock\.json|yarn\.lock'''
tags = ["allowlist"]

[[rules]]
id = "allow-docs"
description = "Allow documentation"
regex = '''README\.md|\.md$'''
tags = ["allowlist"]

# Allowlist for placeholder values
[allowlist]
regexes = [
  '''mongodb\+srv:\/\/<username>:[^@]+@<cluster>\.mongodb\.net\/<database>\?retryWrites=true&w=majority''',
  '''mongodb\+srv:\/\/<username>:[^@]+@<cluster>\.mongodb\.net\/<[^>]+-database>\?retryWrites=true&w=majority''',
  '''example-not-a-secret-[a-z-]+''',
  '''mongodb\+srv:\/\/<username>:<password>@[^\/]+\/<database>\?retryWrites=true&w=majority''',
  '''example-not-a-secret(-[a-z-]+)*''',
  '''dev-.*-change-me'''
]
