services:
  - type: web
    name: marrakech-dunes-backend
    runtime: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: <your-mongo-uri>
      - key: SESSION_SECRET
        sync: false
      - key: SUPERADMIN_PASSWORD
        sync: false
      - key: ADMIN_PASSWORD
        sync: false

      # WhatsApp configuration
      - key: CLIENT_URL
        value: https://marrakechdunes.vercel.app,http://localhost:5173
      - key: WHATSAPP_RECEIVERS
        sync: false
      - key: PORT
        value: 5000
    disk:
      name: marrakech-assets
      mountPath: /app/attached_assets
      sizeGB: 1
    healthCheckPath: /api/health
    autoDeploy: true