services:
  - type: web
    name: MarrakechDunesR
    runtime: node
    buildCommand: |
      npm ci --ignore-scripts --no-audit --no-fund
      npm -w server run build
    startCommand: npm -w server run start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: <your-mongo-uri>
      - key: SESSION_SECRET
        sync: false
      - key: SUPERADMIN_PASSWORD
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      # WhatsApp configuration
      - key: CLIENT_URL
        value: https://marrakechdunes.vercel.app,http://localhost:5173
      - key: WHATSAPP_RECEIVERS
        sync: false
      # Do NOT define PORT here. Render sets PORT automatically.
    disk:
      name: marrakech-assets
      mountPath: /app/attached_assets
      sizeGB: 1