name: E2E Production Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '7 3 * * *'  # Daily at 3:07 AM UTC
  push:
    branches: [main]

jobs:
  e2e-prod:
    name: E2E Production Smoke Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Use public npm registry
      run: |
        cat > .npmrc << 'EOF'
        registry=https://registry.npmjs.org/
        fund=false
        audit=false
        EOF

    - name: Install dependencies
      run: npm ci --ignore-scripts --no-audit --no-fund

    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium

    - name: Run E2E tests against production
      run: npm run test:e2e
      env:
        CI: true

    - name: Upload test results on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7

    - name: Report status
      run: |
        echo "✅ E2E production tests completed successfully"
        echo "Frontend: https://marrakechdunes.vercel.app/"
        echo "Backend: https://marrakechdunesr.onrender.com/api/health"
