name: secret-scan
on:
  push:
  pull_request:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_$(uname -s)_$(uname -m).tar.gz \
          | tar -xz && sudo mv gitleaks /usr/local/bin/gitleaks

      - name: Run Gitleaks
        run: gitleaks detect --no-banner --redact --config .gitleaks.toml
